using System.ComponentModel.DataAnnotations;

namespace Cognify.Server.Models;

public enum PendingQuizStatus
{
    Generating = 0,
    Ready = 1,
    Failed = 2
}

public enum QuizDifficulty
{
    Beginner = 1,
    Intermediate = 2,
    Advanced = 3,
    Professional = 4
}

/// <summary>
/// Represents a quiz that is being generated or awaiting user approval.
/// </summary>
public class PendingQuiz
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid UserId { get; set; }

    public Guid NoteId { get; set; }

    public Guid ModuleId { get; set; }

    [Required]
    [MaxLength(200)]
    public required string Title { get; set; }

    public QuizDifficulty Difficulty { get; set; } = QuizDifficulty.Intermediate;

    /// <summary>
    /// Question type requested. Use QuestionType enum value or -1 for Mixed.
    /// </summary>
    public int QuestionType { get; set; }

    public int QuestionCount { get; set; } = 5;

    /// <summary>
    /// The actual number of questions generated by the AI.
    /// </summary>
    public int? ActualQuestionCount { get; set; }

    public PendingQuizStatus Status { get; set; } = PendingQuizStatus.Generating;

    /// <summary>
    /// Generated questions stored as JSON (same format as Question entity).
    /// </summary>
    public string? QuestionsJson { get; set; }

    public string? ErrorMessage { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    public User? User { get; set; }
    public Note? Note { get; set; }
    public Module? Module { get; set; }
}
